Fix missing-prototypes
model_user.c:395:1: error: no previous prototype for 'places_bookmarks_user_create' [-Werror=missing-prototypes]
model_volumes.c:572:1: error: no previous prototype for 'places_bookmarks_volumes_create' [-Werror=missing-prototypes]
model.c:141:1: error: no previous prototype for 'places_bookmark_group_create' [-Werror=missing-prototypes]
model_system.c:267:1: error: no previous prototype for 'places_bookmarks_system_create' [-Werror=missing-prototypes]
button.c:85:29: error: no previous prototype for 'places_button_get_type' [-Werror=missing-prototypes]
button.c:281:1: error: no previous prototype for 'places_button_new' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>